version: "3.1"

services:
    db:
        image: mariadb
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: dbname
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        depends_on:
            - db
        networks:
            - app-network
        environment:
            PMA_HOST: db

    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        image: anhphat-backend-api
        volumes:
            - .:/app
            - ./node_modules:/app/node_modules
        networks:
            - app-network
        command: npm run dev
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_DIALECT: mariadb
            DB_PORT: 3306
            DB_USERNAME: root
            DB_PASSWORD: 12345
            DB_DATABASE: dbname
            FRONTEND_ORIGIN: "*"
            PORT: 5000
            JWT_SECRET: "Do not use this key on production!"

networks:
    app-network:
        driver: bridge
