version: "3.1"

services:
    db:
        image: mariadb
        restart: always
        ports:
            - 3306:3306
        environment:
            MARIADB_ROOT_PASSWORD: 12345

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
